config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks" }
  root 'welcome#index'

  get '/plans', to: 'welcome#plans'
  get '/examples', to: 'welcome#examples'
  get '/about', to: 'welcome#about'
  get '/builder', to: 'builder#index'
  get 'builder/view', to: 'builder#view'

  post 'builder/update', to: 'builder#update'

  resources :sections

end

app/models/section.rb
class Section < ActiveRecord::Base
    belongs_to :user
    belongs_to :section_type
    has_many :section_text_items

    after_save :do_after_save

    def do_after_save
        # Grab all the section fields for this model and create empty
        # records for each field type
        self.section_type.section_fields.each do |field|
            model_name = "Section#{field.field_table_name.capitalize}Item"
            klass = model_name.constantize

            if klass.create(section_id: self.id, section_field_id: field.id)
                puts "[SUCCESS] #{model_name} added for section: #{self.id}"
            else
                puts "[ERROR] Could not add #{model_name} for section: #{self.id}"
            end
        end
    end
end

app/models/section_field.rb
class SectionField < ActiveRecord::Base
    belongs_to :section_type
    has_one :section_text_item
end

app/models/section_text_item.rb
class SectionTextItem < ActiveRecord::Base
    belongs_to :section
    has_one :section_field
end

app/models/section_type.rb
class SectionType < ActiveRecord::Base
   has_one :section 
   has_many :section_fields
end

app/models/user.rb
class User < ActiveRecord::Base
    # Include default devise modules. Others available are:
    # :confirmable, :lockable, :timeoutable and :omniauthable
    devise :database_authenticatable, :rememberable, :trackable, :omniauthable
    has_many :sections, dependent: :destroy

    def self.connect_to_linkedin(auth, signed_in_resource = nil)
        user = User.where(provider: auth.provider, uid: auth.uid).first
        if user
            return user
        else
            registered_user = User.where(email: auth.info.email).first
            if registered_user
                return registered_user
            else
                puts "[INFO] Creating user"
                puts auth.to_yaml
                User.create(
                    name: auth.info.name,
                    provider: auth.provider,
                    uid: auth.uid,
                    email: auth.info.email,
                    password: Devise.friendly_token[0, 20]
                )
            end
        end
    end  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    # Prevent CSRF attacks by raising an exception.
    # For APIs, you may want to use :null_session instead.
    protect_from_forgery with: :exception

    def after_sign_in_path_for(resource)
        builder_path
    end
end

app/controllers/builder_controller.rb
class BuilderController < ApplicationController
    def initialize
        super
        @publicPath = Rails.root.join('public')
    end

    def index
        @sectionTypes = SectionType.all
        @sections = Section.where(user_id: current_user.id)
    end

    def view
        # Tells the template how to reach its resources
        # The template should be using this for every http request
        @path = '/templates/zach'
        @homeSection = Section.where(user_id: current_user.id).first
        @nameField = { text: '' }
        @addressField = { text: '' }
        begin
            @nameField = @homeSection.section_text_items.first
            @addressField = @homeSection.section_text_items[1]
        rescue
        end
        render "#{@publicPath.to_s}/#{@path}/index.html.erb", layout: false
    end

    def update
        flash[:notice] = "Updated"

    end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController   

    def linkedin
        auth = env["omniauth.auth"]
        @user = User.connect_to_linkedin(request.env["omniauth.auth"], current_user)
        if @user.persisted?
            flash[:notice] = I18n.t "devise.omniauth_callbacks.success"
            sign_in_and_redirect @user, event: :authentication
        else
            session["devise.linkedin_uid"] = request.env["omniauth.auth"]
            redirect_to new_user_registration_url
        end
    end
end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController
    def create
        section_type_id = params[:section_type_id]
        section_type = SectionType.where(id: params[:section_type_id]).first
        if section_type
            section = Section.new(
               section_type_id: section_type.id,
               user_id: current_user.id
            )
            if section.save
                flash[:notice] = "Section added!!"
            else
                flash[:alert] = "Section could not be added :*("
            end
        else
            flash[:alert] = "Not a valid section type"
        end
        redirect_to controller: :builder, action: :index
    end

    def update
        section_id = params[:id]

        # Pull any keys that start with "section_"
        input_items = { }
        params.each do |key, val|
            next if not key.start_with? 'section_'
            tokens = key.split('_', 4)
            puts tokens.to_yaml
            item = {
                type: tokens[1],
                id: tokens[2],
                field: tokens[3]
            }
            input_items[item[:type]] ||= { }
            input_items[item[:type]][item[:id]] ||= { }
            input_items[item[:type]][item[:id]][item[:field]] = val
        end

        input_items.each do |type, item| 
            klass = "Section#{type.capitalize}Item".constantize
            item.each do |id, item2|
                puts '[INFO] previewing id'
                puts id.to_i.inspect
                instance = klass.send(:where, id: id.to_i).first
                item2.each do |field, val|
                    instance[field] = val
                end
                instance.save
            end
        end
        redirect_to controller: :builder, action: :index
    end

    def delete

    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

    def index

    end
    def plans

    end
    def about

    end
    def contact

    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/section_helper.rb
module SectionHelper
end

app/views/builder/index.html.erb
<div class="row">
	<div class="col-md-12">
		<h1>Page Builder</h1>
	</div>
</div>

<div class="row">
    <div class="col-sm-7">
        <div class="wrapper">
            <iframe src="<%= builder_view_path %>"></iframe>
        </div>
    </div>
    <div class="col-sm-5">
    	<div class="add-section">
    		<%= form_tag(sections_path, { class: 'form-horizontal' }) do %>
            	<select name="section_type_id">
                	<% @sectionTypes.each do |type| %>
                    	<option value="<%= type.id %>"><%= type.name %></option>
                	<% end %>
            	</select>
            	<button type="submit" class="btn btn-update">Add Section</button>
        	<% end %>
    	</div>
    	<!-- Nav tabs -->
		<ul class="nav nav-tabs">
  			<% @sections.each_with_index do |section, key| %>
            <li class="<%= key == 0 ? 'active':'' %>"><a href="#<%= section.id %>"data-toggle="tab"><%= section.section_type.name %></a></li>
            <% end %>
		</ul>
    	<div class="wrapper form">
    	<div class="tab-content">
        	<% @sections.each_with_index do |section, key| %>
    			<div class="tab-pane <%= key == 0 ? 'active':'' %>" id="<%= section.id %>">
					<%= form_tag(section_path(section), { class: 'form-horizontal', method: 'PUT' }) do %>
						<div class="form-group">
							<div class="col-sm-12">
								<button type="submit" class="btn btn-remove">Remove Section</button>
							</div>
						</div>
						<div class="form-group">
							<div class="col-md-12">
								<% section.section_type.section_fields.each do |field| %>
									<% item = field.send("section_#{field.field_table_name}_item") %>
									<%= render "partials/#{field.field_table_name}", field: field, item: item %>
								<% end %>
							</div>
						</div>
						<div class="form-group">
							<div class="col-sm-12">
								<button type="submit" class="btn btn-update heightFix">Update</button>
							</div>
						</div>
					<% end %>
				</div>
        	<% end %>
       		</div><!--end tab-content-->
      	</div>
    </div>
</div>

<footer>
	<div class="footer">
	</div>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>RecsyRails</title>
        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
        <link rel="stylesheet/less" type="text/css" href="/bootstrap/less/bootstrap.less" />
        <link rel="stylesheet/less" type="text/css" href="/bootstrap/less/custom.less" />
        <link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">
        <link rel="stylesheet/less" type="text/css" href="/builder.less">
        <script src="//cdnjs.cloudflare.com/ajax/libs/less.js/1.7.0/less.min.js"></script>
        <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
        <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
        <script src="/js/custom.js"></script>
        <%= csrf_meta_tags %>
    </head>
    <body>
    <header>
    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/"><img src="/images/logo.png" width="500%" height="150%" class="logo" /></a>
        </div>
        <div class="collapse navbar-collapse navbar-right">
          <ul class="nav navbar-nav">
            <li><a href="/plans">Plans and Pricing</a></li>
            <li><a href="/examples">Website Examples</a></li>
            <li><a href="/about">About Recsy</a></li>
            	<% if user_signed_in? %>
    				<li><p class="signedin">Signed in as <%= current_user.name %>. Not you? &nbsp;<%= link_to "Sign out", destroy_user_session_path, method: :delete %></p></li>
					<% else %>
    				<li><%= link_to "Sign in/Register with Linkedin", user_omniauth_authorize_path(:linkedin) %></li>
				<% end %>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    	</div>
   	</header>
    <div class="container">
        <% if notice %>
            <div class="alert alert-warning fade in">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                <%= notice %>
            </div>
        <% end %>
        <% if alert %>
            <div class="alert alert-warning fade in">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                <%= alert %>
            </div>
        <% end %>
        <%= yield %>
    </div>
     <footer class="footer-3">
		<div class="container">
			<div class="row text-center">
				<div class="col-sm-12">
					<h6>Nashville, TN</h6>
					<div class="address">
						Built at HackNashville 5
					</div>
				</div>
			</div>
		</div>
    </footer>
</body>
</html>

app/views/partials/_text.html.erb
<div class="form-group">
    <label class="col-sm-2 control-label"><%= field.label %></label>
    <div class="col-sm-10">
        <input type="hidden" name="section_<%= field.field_table_name %>_<%= item.id %>_section_field_id" value="<%= field.id %>">
        <input type="text" class="form-control" name="section_<%= field.field_table_name %>_<%= item.id %>_text" value="<%= item.text %>">
    </div>
</div>

app/views/welcome/about.html.erb
<style>body{background-image:background: url('http://subtlepatterns.com/patterns/fabric_of_squares_gray.png'); background-repeat:repeat;}</style>
    	<div class="page-wrapper">
			<div class="container">
				<h1>Relax.</h1>
				<p class="lead">Let us take the <i>stress</i> out of your next career step</p>
				<div class="row">
					<div class="col-md-12">
						<img src="/../images/recsy..job.png" width="75%" class="center-block"/>
						<br>
						<br>
						<br>
						<p>Sign in with LinkedIn and see your personal website come to life in seconds. Upload your projects and let people see what makes you you. <b>56% of hiring managers</b> were more impressed with a candidate's website than any other branding tool. What's a better way to spend the next five minutes?</p>
						<br>
						<p><b>Who are we?</b> We're your career expert, cheerleader, personal website builder, connection to recruiters. We're two recent college grads who <i>get</i> what it's like to have to represent yourself on one black-and-white page when you're <i>so</i> much more than a resume. At Recsy, we want the <i>real</i> you to shine in a way that gets <b>noticed</b> by recruiters.</p>
						<br>
						<p>Finding a job, internship, or getting into grad school is hard. Let Recsy make it easier for you. So relax ;). You've earned it.</p>
						<br>
					</div>
				</div>
			</div>
        </div>

app/views/welcome/contact.html.erb
<style>
    .row {
        margin-top: 20px;
    }
    .preview-wrapper {
        padding: 5px;
        background-color: #333;
    }
    iframe {
        width: 100%;
        min-height: 500px;
        border-width: 0;
        outline: 0;
        background-color: #EEE;
    }
</style>
<div class="row">
    <div class="col-sm-7">
    	<%= form_for :article do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>
    </div>
    <div class="col-sm-5">
oh haayy

    </div>
</div>

app/views/welcome/examples.html.erb
<style>body{background: url('http://subtlepatterns.com/patterns/fabric_of_squares_gray.png'); background-repeat:repeat;}.banner2{height:600px;}</style>

<div class="container banner2">
	<h1>Website Examples</h1>
	<p class="lead">Some of our favourites</p>
	<div class="row text-center">
		<div class="col-sm-4">
			<p>TaylorBayles.com</p>
			<a href="http://www.taylorbayles.com"><img src="/../images/websiteExample1.png" class="img-responsive"/></a>
		</div>
		<div class="col-sm-4">
			<p text-align="center">ZachBoyette.com</p>
			<a href="http://www.zachboyette.com"><img src="/../images/websiteExample2.png" class="img-responsive"/></a>
		</div>
		<div class="col-sm-4">
			<p text-align="center">MarissaMontgomery.com</p>
			<a href="http://www.marissamontgomery.com"><img src="/../images/websiteExample3.png" class="img-responsive"/></a>
		</div>
	</div>
</div>

app/views/welcome/index.html.erb
<style>body{background: url('/images/ipad.png'); background-repeat: no-repeat; background-size: 1440px;}.banner{font-family:Oswald; sans-serif;}footer{display: none;}</style>
<div class="banner home">
    		<div class="row">
    			<h1>Hi! We're Recsy,</h1>
    			<h2>your new:</h2>
    			<h2 class="rotate">Career Coach, Personal Website Creator, Recruiter Connecter, Online Presence</h2>
    			<% if user_signed_in? %>
    				<a href="/builder" class="btn btn-lg btn-primary">Create Your Website</a>
					<% else %>
					<a href="/users/auth/linkedin" class="btn btn-lg btn-primary">Log In With LinkedIn</a>
				<% end %>


    		</div><!--end row-->
    	</div><!-- /.container -->
	 </div><!--end homebanner-->

app/views/welcome/plans.html.erb
<style>body{background: url('http://subtlepatterns.com/patterns/fabric_of_squares_gray.png'); background-repeat:repeat;}</style>

            <!-- price-1 -->
            <section class="price-1">
                <div class="container">
                    <h1>Get Started With Our Plans</h1>
                    <p class="lead">
                        Start impressing recruiters today
                    </p>
                    <div class="row plans">
                        <div class="col-sm-6">
                            <div class="plan">
                                <div class="title">Starter</div>
                                <div class="price"><b>$8.99</b>/month for 3 months<br><b>$6.99</b>/month for 12 months</div>
                                <div class="description">
                                	up to <b>5</b> templates<br>
                                    image upload<br>
                                    <b>free</b> domain name<br>
                                    <b>unlimited</b> updates<br>
                                    <br>
                                    <br>
                                </div>
                                <a class="btn btn-primary" href="#">Choose this plan</a>
                            </div>
                        </div>
                        <div class="col-sm-6">
                            <div class="plan">
                                <div class="title">Professional</div>
                                <div class="price"><b>$11.99</b>/month for 3 months<br><b>$9.99</b>/month for 12 months</div>
                                <div class="description">
                                    <b>20+</b> templates<br>
                                    image upload<br>
                                    <b>free</b> domain name<br>
                                    <b>unlimited</b> updates<br>
                                    listed for recruiters<br>
                                    <b>free</b> inbox<br>
                                </div>
                                <a class="btn btn-default">Coming Soon!</a>

                                <div class="ribbon label label-warning">Coming Soon!</div>
                            </div>
                        </div>

                    </div>
                </div>
            </section>